name: CI workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: conf
        uses: cupcakearmy/confluence-markdown-sync@v1.0.1
        with:
          from: './docs.md'
          to: '320187336' # The confluence page id where to write the output
          cloud: ${{ secrets.cloud }}
          user: ${{ secrets.user }}
          token: ${{ secrets.token }}